apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    env: demo
