apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    env: demo
  name: nginx-rc
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3
